name: Build Glare
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: 22
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.10.2
      - name: Build
        run: gradle build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Glare
          path: |
            build/libs/glare-editor-*.jar
            build/libs/glare-engine-*.jar
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/glare-editor-*.jar
            build/libs/glare-engine-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}